services:
  server:
    build:
      context: .
    image: us-central1-docker.pkg.dev/dulcet-asset-448300-k9/nilay-100964543/assignment2
    environment:
      NODE_ENV: production
    ports:
      - 8080:3000
